// Every photo ships as a 1x and a 2x WebP, both generated by scripts/optimize-images.mjs
// from the originals in assets-source/. The glob keeps a picture's two variants together
// instead of needing two import lines per image.
const files = import.meta.glob('./assets/img/*.webp', { eager: true, query: '?url', import: 'default' })

const url = name => {
    const file = files[`./assets/img/${name}.webp`]
    if (!file) throw new Error(`missing image "${name}" - run: npm run optimize:images`)
    return file
}

// spread onto an <img>: gives it src plus the retina variant
export const image = name => ({ src: url(name), srcSet: `${url(name)} 1x, ${url(`${name}@2x`)} 2x` })
